// Blackbox of the analogue_interface hard macro (dry-run version: placed blocks and dummies, not routed).
// Generated by scripts/build_analogue_interface.py.

module analogue_interface (
`ifdef USE_POWER_PINS
    inout  wire VPWR,
    inout  wire VAPWR,
    inout  wire VGND,
`endif
    input  wire [7:0] adc_ref,
    input  wire adc_hold,
    output wire adc_comp,
    input  wire [15:0] dac_out,
    input  wire [3:0] sh_cap_en,
    inout  wire analog_0,
    inout  wire analog_1,
    inout  wire analog_2
);
endmodule
